In [1]:
import numpy as np 

<Br>

# 0D (Zero Dimention) tensor:

<Br>

In [4]:
zero_d = np.array(4)

print(f"zero_d : {zero_d}")

print(f"zero_d : {type(zero_d)}")

print(f"dimention: {zero_d.ndim}")

zero_d : 4
zero_d : <class 'numpy.ndarray'>
dimention: 0


<br>

# 1D Tensor:

<br>

In [6]:
one_d = np.array([1,2,3,4,5])

print(f"one_d : {one_d}")

print(f"one_d : {type(one_d)}")

print(f"dimention: {one_d.ndim}")

one_d : [1 2 3 4 5]
one_d : <class 'numpy.ndarray'>
dimention: 1


<br>

# 2D Tensor:

<br>

In [11]:
two_d = np.array([
                 [1,2,3,4,5],
                 [6,7,8,9,10],
                 [11,12,13,14,15]
                 ]
                 )

print(f"two_d : \n\n {two_d}\n\n")

print(f"two_d : {type(two_d)}")

print(f"dimention: {two_d.ndim}")

two_d : 

 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


two_d : <class 'numpy.ndarray'>
dimention: 2
