<br>
<br>

# Test the Model: (That we make without using pipeline:)

<br>
<br>

# Production code:

In [1]:

import pickle 
import numpy as np 

In [2]:

wp_embarked = pickle.load(open("model/without_pipeline_embarked",'rb'))
wp_sex = pickle.load(open("model/without_pipeline_sex.pkl",'rb'))
wp_model = pickle.load(open('model/without_pipeline.pkl','rb'))


<br>
<br>

# Test_User:

<br>
<br>

In [3]:
# 'Age,'Sex','Embarked','Pclass', 'SibSp', 'Parch', 'Fare':

test_input = np.array([31.0,'male','S',2, 0, 0, 10.5]).reshape(7,1)
test_input.shape

(7, 1)

<br>

# use those model:

<br>

In [6]:
test_input[2:3].reshape(1,1)

array([['S']], dtype='<U32')

In [5]:
test_input_sex = wp_sex.transform(test_input[1:2].reshape(1,1))
test_input_sex

/home/yasin/allProgram/machine_learning/code/mlEnv/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[1.]])

In [9]:
test_input_embarked = wp_embarked.transform(test_input[2:3].reshape(1,1))
test_input_embarked

array([[0., 1.]])

In [12]:
test_input_age = test_input[:1].reshape(1,1)
test_input_age.shape

(1, 1)

In [17]:
test_input_rem = np.array([2, 0, 0, 10.5]).reshape(1,4)
test_input_rem.shape

(1, 4)

In [19]:
test_transformed = np.concatenate((test_input_age,test_input_sex,test_input_embarked,test_input_rem),axis=1)
test_transformed

array([['31.0', '1.0', '0.0', '1.0', '2.0', '0.0', '0.0', '10.5']],
      dtype='<U32')

In [20]:
y_pridt = wp_model.predict(test_transformed)
y_pridt

array([0])


<br>
<br>

`অর্থাৎ, Production level এ আমাদের অনেক কোড করতে হচ্ছে এর জন্যও Pipeline আমাদের দরকার । Easiest way . `

<br>
<br>
