In [90]:

import numpy as np 
import pandas as pd 
from sklearn.model_selection import train_test_split


In [91]:
class myLinearRegression:
    
    def __init__(self):
        self.m = None
        self.b = None
        
    def fit(self,X_train,y_train):
        num = 0
        den = 0
        for i in range(X_train.shape[0]):
            num += (X_train[i] - X_train.mean()) * (y_train[i] - y_train.mean())
            den += (X_train[i] - X_train.mean())**2
        
        self.m = num/den
        self.b = y_train.mean() - (self.m*X_train.mean())
        print(self.m,"  ",self.b)
        
    
    def predict(self,X_test):
        return self.m*X_test +self.b 
    

In [92]:
df = pd.read_csv("dataset/50_placement.csv")
df.sample(4)

cgpa  package
99   6.61     3.24
53   6.47     2.61
110  8.18     3.76
138  7.91     3.89

In [93]:
X_train,X_test,y_train,y_test = train_test_split(
    df["cgpa"],
    df["package"],
    test_size=0.2,
    random_state=2
)


In [94]:
y_train.values

array([3.13, 3.91, 2.25, 2.3 , 4.06, 3.18, 2.7 , 2.49, 3.15, 2.99, 4.08,
       4.14, 2.6 , 2.44, 2.71, 2.72, 1.63, 2.31, 2.51, 3.5 , 2.24, 2.58,
       2.42, 2.54, 4.37, 2.17, 3.14, 2.19, 3.54, 1.54, 2.72, 3.98, 2.46,
       3.  , 1.98, 2.65, 3.75, 3.67, 2.93, 3.08, 2.21, 2.84, 3.76, 3.03,
       2.09, 3.26, 2.16, 2.7 , 3.83, 2.88, 3.16, 3.04, 3.13, 3.04, 4.6 ,
       3.26, 2.85, 2.09, 3.31, 3.89, 1.87, 3.11, 2.4 , 3.48, 3.08, 2.76,
       2.93, 3.39, 2.35, 3.08, 2.14, 3.24, 1.73, 3.24, 3.44, 2.69, 3.33,
       2.42, 2.57, 3.55, 2.66, 1.53, 2.98, 2.84, 3.52, 3.16, 3.82, 2.6 ,
       1.61, 2.2 , 2.99, 3.12, 2.74, 2.83, 2.77, 2.35, 2.19, 3.42, 4.02,
       3.89, 3.15, 3.99, 3.42, 3.08, 2.46, 2.61, 3.49, 3.76, 2.82, 4.03,
       2.99, 2.73, 2.18, 3.09, 3.96, 2.1 , 3.33, 4.62, 3.47, 2.48, 4.43,
       4.11, 3.44, 3.18, 3.02, 4.06, 2.26, 1.48, 2.94, 2.89, 2.72, 3.09,
       2.73, 4.36, 3.  , 3.79, 2.59, 2.87, 3.57, 1.37, 3.6 , 2.43, 3.33,
       2.31, 3.4 , 3.89, 4.25, 3.26, 3.67, 2.79, 3.

In [95]:
lr = myLinearRegression()

lr.fit(X_train.values,y_train.values)


0.5579519734250721    -0.8961119222429152


In [96]:
print(f"X_test[0]: {X_test.values[0]}")
print(f"y_test[0]: {y_test.values[0]}")
lr.predict(X_test.values[0].reshape(1,1)) # result is not good should be 4.1

X_test[0]: 8.58
y_test[0]: 4.1


array([[3.89111601]])

In [98]:
print(f"X_test[0]: {X_test.values[1]}")
print(f"y_test[0]: {y_test.values[1]}")
lr.predict(X_test.values[1].reshape(1,1)) # result is not good should be 3.49

X_test[0]: 7.15
y_test[0]: 3.49


array([[3.09324469]])