In [14]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns
import plotly.express as px 
import plotly.graph_objects as go 
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_regression
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [5]:
X,y = make_regression(n_samples=100,n_features=2,n_informative=2,n_targets=1,noise=50)

In [7]:
df = pd.DataFrame({'feature1':X[:,0], 'feature2':X[:,1],'target':y})
df.sample(5)

feature1  feature2      target
24 -0.022079  1.822656  107.045248
72  0.968405  0.758324   77.174074
67  0.331604 -0.375310   36.875838
80  0.578178  0.317809   67.540933
64  0.063547 -0.175255  -12.170404

In [13]:
fig = px.scatter_3d(x=df['feature1'],y=df['feature2'],z=df['target'],
    height=700,width=900)

fig.show()


In [19]:
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=3,test_size=0.2)

In [20]:
lr = LinearRegression()
lr.fit(X_train,y_train)

LinearRegression()

In [22]:
y_pred = lr.predict(X_test)
print("MAE: ",mean_absolute_error(y_test,y_pred))
print("MSE: ",mean_squared_error(y_test,y_pred))
print("R2 : ",r2_score(y_test,y_pred))

MAE:  35.86826202711326
MSE:  1866.101031730533
R2 :  0.7492264592668123


In [25]:
np.linspace(-5,5,10) # we get 10 number between -5 to 5 

array([-5.        , -3.88888889, -2.77777778, -1.66666667, -0.55555556,
        0.55555556,  1.66666667,  2.77777778,  3.88888889,  5.        ])

<br>

### Mesh grid: [link](https://www.youtube.com/watch?v=7K_a1mmraHU)

In [29]:
x = np.linspace(-5,5,10)
y = np.linspace(-5,5,10)

xGrid,yGrid  = np.meshgrid(y,x)
xGrid

array([[-5.        , -3.88888889, -2.77777778, -1.66666667, -0.55555556,
         0.55555556,  1.66666667,  2.77777778,  3.88888889,  5.        ],
       [-5.        , -3.88888889, -2.77777778, -1.66666667, -0.55555556,
         0.55555556,  1.66666667,  2.77777778,  3.88888889,  5.        ],
       [-5.        , -3.88888889, -2.77777778, -1.66666667, -0.55555556,
         0.55555556,  1.66666667,  2.77777778,  3.88888889,  5.        ],
       [-5.        , -3.88888889, -2.77777778, -1.66666667, -0.55555556,
         0.55555556,  1.66666667,  2.77777778,  3.88888889,  5.        ],
       [-5.        , -3.88888889, -2.77777778, -1.66666667, -0.55555556,
         0.55555556,  1.66666667,  2.77777778,  3.88888889,  5.        ],
       [-5.        , -3.88888889, -2.77777778, -1.66666667, -0.55555556,
         0.55555556,  1.66666667,  2.77777778,  3.88888889,  5.        ],
       [-5.        , -3.88888889, -2.77777778, -1.66666667, -0.55555556,
         0.55555556,  1.66666667,  2.77777778

In [30]:

final = np.vstack((xGrid.ravel().reshape(1,100),yGrid.ravel().reshape(1,100))).T
z_final = lr.predict(final).reshape(10,10)
z = z_final


In [31]:
ig = px.scatter_3d(df, x='feature1', y='feature2', z='target')

fig.add_trace(go.Surface(x = x, y = y, z =z ))

fig.show()

In [32]:
lr.coef_

array([63.38334797, 42.01776931])

In [33]:
lr.intercept_

-2.2075842218747024